title: Seeing With Sound Dataset
description: Dataset page for the CVPR 2023 paper Seeing With Sound Long-range Acoustic Beamforming for Multimodal Scene Understanding
theme: just-the-docs
color_scheme: foo
url: https://jimaldon.github.io/seeingwithsound
search_enabled: false
baseurl: /seeingwithsound
  #logo: "/assets/img/logo.jpg"
favicon_ico: "/assets/img/favicon.ico"
